version: '3.8'

services:
  prompt-nest:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    container_name: promptnest
    volumes:
      - prompt-nest-data:/data
    restart: unless-stopped

volumes:
  prompt-nest-data:
